# Generated by Django 4.2.4 on 2023-11-27 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_seen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('slug', 'user', 'category')},
        ),
    ]
