# Generated by Django 4.2.4 on 2023-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_member_message_member_not_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
