# Generated by Django 4.2.4 on 2023-11-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='position',
        ),
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
